name: Build APK

on:
  push:
    branches:
      - main  # Replace with your branch if needed
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Python version required

      - name: Install Buildozer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            python3-setuptools \
            python3-dev \
            git \
            zip \
            unzip \
            openjdk-8-jdk \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libreadline-dev \
            libssl-dev \
            libffi-dev \
            libsqlite3-dev \
            libbz2-dev \
            liblzma-dev \
            zlib1g-dev

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk  # Make sure the APK file name matches
